### ISSUE TITLE
pings to hostnames are unreliable

### ISSUE THREAD

**Issue by michaelosthege** [stellarbit/aioping#10]
I'm trying to use this library, however when I try to ping a hostname, I get timeouts almost all the time.

For example, the following code:

```python
import asyncio
import aioping
	
loop = asyncio.get_event_loop()

for host in ['127.0.0.1', 'localhost']:
	loop.run_until_complete(aioping.verbose_ping(host, count=10))
```

Returns:

```
127.0.0.1 get ping in 0.8905ms
127.0.0.1 get ping in 0.8746ms
127.0.0.1 get ping in 1.1818ms
127.0.0.1 get ping in 0.9671ms
127.0.0.1 get ping in 1.4835ms
127.0.0.1 get ping in 1.4183ms
127.0.0.1 get ping in 0.9092ms
127.0.0.1 get ping in 0.9558ms
127.0.0.1 get ping in 1.4437ms
127.0.0.1 get ping in 1.1956ms

localhost get ping in 2.0482ms
localhost failed: Ping timeout
```

I want to use it on Python 3.6 on Windows. I have tested it under Python 3.5 and 3.6 on Windows, Docker on Windows and Docker on Raspberry Pi, but it's unreliable on all platforms.

In Docker, it printed some error messages:

```
Exception in callback sendto_ready(packet=b'\x80\x00O%\...QQQQQQQQQQQQQ', socket=<socket.socke...:', 58, 0, 0)>, dest=('::1', 0, 0, 0), future=<Future pendi...x75fc48d0>()]>)() at /usr/local/lib/python3.6/site-packages/aioping/__init__.py:179
handle: <Handle sendto_ready(packet=b'\x80\x00O%\...QQQQQQQQQQQQQ', socket=<socket.socke...:', 58, 0, 0)>, dest=('::1', 0, 0, 0), future=<Future pendi...x75fc48d0>()]>)() at /usr/local/lib/python3.6/site-packages/aioping/__init__.py:179>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/aioping/__init__.py", line 180, in sendto_ready
    socket.sendto(packet, dest)
OSError: [Errno 99] Cannot assign requested address
```

Can you reproduce it?
Am I doing something completely wrong here?

**Comment by JackSlateur** [comment]
Is not this specific to 'localhost' ?

**Comment by michaelosthege** [comment]
I just checked again, but it also fails on other hosts:

```
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import aioping
>>> import asyncio
>>> loop = asyncio.get_event_loop()
>>> for host in ['192.168.178.30', 'JURZ']:
...     loop.run_until_complete(aioping.verbose_ping(host, count=10))
...
192.168.178.30 get ping in 10.3139ms
192.168.178.30 get ping in 4.4923ms
192.168.178.30 get ping in 3.2963ms
192.168.178.30 get ping in 3.1487ms
192.168.178.30 get ping in 3.5433ms
192.168.178.30 get ping in 3.1220ms
192.168.178.30 get ping in 3.0960ms
192.168.178.30 get ping in 3.1101ms
192.168.178.30 get ping in 3.9832ms
192.168.178.30 get ping in 3.2649ms

JURZ get ping in 3.2902ms
JURZ failed: Ping timeout

>>> for host in ['192.168.178.30', 'JURZ.fritz.box']:
...     loop.run_until_complete(aioping.verbose_ping(host, count=10))
...
192.168.178.30 get ping in 6.8614ms
192.168.178.30 get ping in 6.1078ms
192.168.178.30 get ping in 3.7684ms
192.168.178.30 get ping in 3.3082ms
192.168.178.30 get ping in 3.6419ms
192.168.178.30 get ping in 3.3232ms
192.168.178.30 get ping in 2.9326ms
192.168.178.30 get ping in 3.0241ms
192.168.178.30 get ping in 2.8080ms
192.168.178.30 get ping in 3.5965ms

JURZ.fritz.box get ping in 4.5562ms
JURZ.fritz.box get ping in 3.2584ms
JURZ.fritz.box get ping in 3.2162ms
JURZ.fritz.box get ping in 4.1659ms
JURZ.fritz.box get ping in 3.4313ms
JURZ.fritz.box get ping in 15.3258ms
JURZ.fritz.box get ping in 3.4849ms
JURZ.fritz.box failed: Ping timeout

>>>
```

**Comment by anton-belousov** [comment]
@michaelosthege sorry for late reply, this library resolves the hostname first before sending any pings, and after the name is resolved its behavior doesn't differ from when you provide an IP address. I merged some pull requests & added some fixes, so probably it could be fixed for you. I doubt it makes sense for you 1.5 years later, but still.
