### ISSUE TITLE
Infinity loop while pinging host

### ISSUE THREAD

**Issue by zloidemon** [stellarbit/aioping#11]
I got infinity loop with that message, although `ping` command works fine.

```
OSError: [Errno 101] Network is unreachable
Exception in callback sendto_ready()() at /home/vg/venv35/lib/python3.5/site-packages/aioping/__init__.py:179
handle: <Handle sendto_ready()() at /home/vg/venv35/lib/python3.5/site-packages/aioping/__init__.py:179>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/vg/venv35/lib/python3.5/site-packages/aioping/__init__.py", line 180, in sendto_ready
    socket.sendto(packet, dest)
OSError: [Errno 101] Network is unreachable
```

**Comment by anton-belousov** [comment]
Resolved in one of latest merges, please check out the 0.3.0 version.
